title: Biolink Model
email: deepak.unni3@gmail.com
description: A high level datamodel for representing biological entities and their associations.

logo: "/assets/images/biolink-logo.png"

remote_theme: pmarsceill/just-the-docs@v0.3.3

aux_links:
  "Biolink Model on GitHub":
    - "//github.com/biolink/biolink-model"

search_enabled: true
heading_anchors: true

# footer_content: "BioLink Model"

collections:
  docs:
    output: true
  about:
    output: true
  guidelines:
    output: true

includes:
- about
- guidelines
- index.md
