title: Biolink Model
email: deepak.unni3@gmail.com
description: A high level datamodel for representing biological entities and their associations.

logo: "/assets/images/biolink-logo.png"

remote_theme: deepakunni3/just-the-docs

ga_tracking: UA-157380109-1

aux_links:
  "Biolink Model on GitHub":
    - "//github.com/biolink/biolink-model"

search_enabled: true
heading_anchors: true

# footer_content: "BioLink Model"

collections:
  docs:
    output: true

includes:
- about
- _docs
- index.md
