title: BioLink Model
email: deepak.unni3@gmail.com
description: A high level datamodel for representing biological entities and their associations.


remote_theme: deepakunni3/just-the-docs

aux_links:
  "BioLink Model on GitHub":
    - "//github.com/biolink/biolink-model"

search_enabled: true

includes:
- docs
- about
- index.md
