---
site_name: "Biolink Model Documentation"
theme:
  name: material
  palette:
    scheme: black
    primary: cyan
  logo: images/biolink-logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Overview: index.md
  - Using the LinkML Modeling Language: using-the-modeling-language.md
  - Working with Biolink: working-with-the-model.md
  - Infores: information-resource-registry.md
  - Associations with Qualifiers: association-examples-with-qualifiers.md
  - Interpreting a Fully Qualified Edge: reading-a-qualifier-based-statement.md
  - Curating Biolink: curating-the-model.md
  - Maintaining Biolink: maintaining-the-model.md
  - Visualize Categories: categories.html
  - Visualize Predicates: predicates.html
  - Visualize Aspects: aspects.html
  - FAQ: faq.md
site_url: https://biolink.github.io/biolink-model
repo_url: https://github.com/biolink/biolink-model
extra_css:
  - style.css


# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
