id: attribute
schema_generating: true
description: A property or characteristic of an entity. For example, an apple may
  have properties such as color, shape, age, crispiness. An environmental sample may
  have attributes such as depth, lat, long, material.
display_name: attribute
document_category: attribute
weight: 20
fields:
- id: has_attribute_type
  description: connects an attribute to a class that describes it
  display_name: has attribute type
- id: has_quantitative_value
  description: connects an attribute to a value
  display_name: has quantitative value
  cardinality: multi
- id: has_qualitative_value
  description: connects an attribute to a value
  display_name: has qualitative value
- id: id
  description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for a thing
  display_name: name
- id: category
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: category
  cardinality: multi
