display_name: !!python/object/new:biolinkml.meta.ClassDefinitionName
- carbohydrate
document_category: !!python/object/new:biolinkml.meta.ClassDefinitionName
- carbohydrate
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - id
  id: id
- description: A human-readable name for a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - name
  id: name
- cardinality: multi
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - category
  id: category
- cardinality: multi
  description: A relationship that is asserted between two named things
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - related to
  id: related_to
- cardinality: multi
  description: holds between any two entities that directly or indirectly interact
    with each other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - interacts with
  id: interacts_with
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - node property
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - iri
  id: iri
- cardinality: multi
  description: Alternate human-readable names for a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - synonym
  id: synonym
- description: a long-form human readable name for a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - full name
  id: full_name
- description: a human-readable description of a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - description
  id: description
- cardinality: multi
  description: more commonly used for gene symbols in yeast
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - systematic synonym
  id: systematic_synonym
- cardinality: multi
  description: holds between a biological entity and a phenotype, where a phenotype
    is construed broadly as any kind of quality of an organism part, a collection
    of these qualities, or a change in quality or qualities (e.g. abnormally increased
    temperature).
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - has phenotype
  id: has_phenotype
- cardinality: multi
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - molecularly interacts with
  id: molecularly_interacts_with
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one changes the amount of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects abundance of
  id: affects_abundance_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the amount of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases abundance of
  id: increases_abundance_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the amount of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases abundance of
  id: decreases_abundance_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one changes the activity of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects activity of
  id: affects_activity_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the activity of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases activity of
  id: increases_activity_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the activity of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases activity of
  id: decreases_activity_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one changes the level of expression of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects expression of
  id: affects_expression_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the level of expression of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases expression of
  id: increases_expression_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the level of expression of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases expression of
  id: decreases_expression_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one changes the rate or quality of folding of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects folding of
  id: affects_folding_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the rate or quality of folding of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases folding of
  id: increases_folding_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the rate or quality of folding of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases folding of
  id: decreases_folding_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one changes the localization of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects localization of
  id: affects_localization_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the proper localization of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases localization of
  id: increases_localization_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the proper localization of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases localization of
  id: decreases_localization_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the metabolic processing of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects metabolic processing of
  id: affects_metabolic_processing_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the rate of metabolic processing of the other within a system of
    interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases metabolic processing of
  id: increases_metabolic_processing_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the rate of metabolic processing of the other within a system of
    interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases metabolic processing of
  id: decreases_metabolic_processing_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one leads changes in the molecular modification(s) of the other (e.g. via post-translational
    modifications of proteins such as the addition of phosphoryl group, or via redox
    reaction that adds or subtracts electrons)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects molecular modification of
  id: affects_molecular_modification_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one leads to increased molecular modification(s) of the other (e.g. via post-translational
    modifications of proteins such as the addition of phosphoryl group, or via redox
    reaction that adds or subtracts electrons)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases molecular modification of
  id: increases_molecular_modification_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one leads to decreased molecular modification(s) of the other (e.g. via post-translational
    modifications of proteins such as the addition of phosphoryl group, or via redox
    reaction that adds or subtracts electrons)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases molecular modification of
  id: decreases_molecular_modification_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the rate of chemical synthesis of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects synthesis of
  id: affects_synthesis_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the rate of chemical synthesis of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases synthesis of
  id: increases_synthesis_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the rate of chemical synthesis of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases synthesis of
  id: decreases_synthesis_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the rate of degradation of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects degradation of
  id: affects_degradation_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the rate of degradation of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases degradation of
  id: increases_degradation_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the rate of degradation of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases degradation of
  id: decreases_degradation_of
- cardinality: multi
  description: holds between a molecular entity and a genomic entity where the action
    or effect of the molecular entity impacts the rate of mutation of the genomic
    entity within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects mutation rate of
  id: affects_mutation_rate_of
- cardinality: multi
  description: holds between a molecular entity and a genomic entity where the action
    or effect of the molecular entity increases the rate of mutation of the genomic
    entity within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases mutation rate of
  id: increases_mutation_rate_of
- cardinality: multi
  description: holds between a molecular entity and a genomic entity where the action
    or effect of the molecular entity decreases the rate of mutation of the genomic
    entity within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases mutation rate of
  id: decreases_mutation_rate_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the susceptibility of a biological entity or system (e.g. an organism,
    cell, cellular component, macromolecular machine, biological or pathological process)
    to the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects response to
  id: affects_response_to
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the susceptibility of a biological entity or system (e.g. an organism,
    cell, cellular component, macromolecular machine, biological or pathological process)
    to the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases response to
  id: increases_response_to
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the susceptibility of a biological entity or system (e.g. an organism,
    cell, cellular component, macromolecular machine, biological or pathological process)
    to the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases response to
  id: decreases_response_to
- cardinality: multi
  description: holds between a molecular entity and an mRNA where the action or effect
    of the molecular entity impacts the splicing of the mRNA
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects splicing of
  id: affects_splicing_of
- cardinality: multi
  description: holds between a molecular entity and an mRNA where the action or effect
    of the molecular entity increases the proper splicing of the mRNA
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases splicing of
  id: increases_splicing_of
- cardinality: multi
  description: holds between a molecular entity and an mRNA where the action or effect
    of the molecular entity decreases the proper splicing of the mRNA
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases splicing of
  id: decreases_splicing_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the stability of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects stability of
  id: affects_stability_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the stability of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases stability of
  id: increases_stability_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the stability of the other within a system of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases stability of
  id: decreases_stability_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the rate of transport of the other across some boundary in a system
    of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects transport of
  id: affects_transport_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the rate of transport of the other across some boundary in a system
    of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases transport of
  id: increases_transport_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the rate of transport of the other across some boundary in a system
    of interest
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases transport of
  id: decreases_transport_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the rate of secretion of the other out of a cell, gland, or organ
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects secretion of
  id: affects_secretion_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the rate of secretion of the other out of a cell, gland, or organ
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases secretion of
  id: increases_secretion_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the rate of secretion of the other out of a cell, gland, or organ
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases secretion of
  id: decreases_secretion_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one impacts the rate of uptake of the other into of a cell, gland, or organ
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects uptake of
  id: affects_uptake_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one increases the rate of uptake of the other into of a cell, gland, or organ
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - increases uptake of
  id: increases_uptake_of
- cardinality: multi
  description: holds between two molecular entities where the action or effect of
    one decreases the rate of uptake of the other into of a cell, gland, or organ
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - decreases uptake of
  id: decreases_uptake_of
- cardinality: multi
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - regulates, entity to entity
  id: regulates_entity_to_entity
- cardinality: multi
  description: holds between a measurable molecular entity and a disease or phenotypic
    feature, where the entity is used as an indicator of the presence or state of
    the disease or feature.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - biomarker for
  id: biomarker_for
- cardinality: multi
  description: connects a thing to a class representing a taxon
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - in taxon
  id: in_taxon
id: carbohydrate
schema_generating: true
weight: 20
