id: cellular_component
schema_generating: true
description: A location in or around a cell
display_name: cellular component
document_category: cellular component
weight: 20
fields:
- id: id
  description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for a thing
  display_name: name
- id: category
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: category
  cardinality: multi
- id: in_taxon
  description: connects a thing to a class representing a taxon
  display_name: in taxon
  cardinality: multi
