display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- environmental process
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- environmental process
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - id
  id: id
- description: A human-readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - name
  id: name
- cardinality: multi
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - category
  id: category
- description: A grouping for any relationship type that holds between any two things
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - related to
  id: related_to
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - node property
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - iri
  id: iri
- cardinality: multi
  description: Alternate human-readable names for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - synonym
  id: synonym
- description: a long-form human readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - full name
  id: full_name
- description: a human-readable description of a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - description
  id: description
- description: more commonly used for gene symbols in yeast
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - systematic synonym
  id: systematic_synonym
- description: describes an entity that has a direct affect on the state or quality
    of another existing entity. Use of the 'affects' predicate implies that the affected
    entity already exists, unlike predicates such as 'affects risk for' and 'prevents,
    where the outcome is something that may or may not come to be.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - regulates, process to process
  id: regulates_process_to_process
- description: 'holds between a process and a continuant, where the continuant is
    somehow involved in the process '
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - has participant
  id: has_participant
- description: holds between a process and a continuant, where the continuant is an
    input into the process
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - has input
  id: has_input
- description: holds between two processes, where one completes before the other begins
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - precedes
  id: precedes
id: environmental_process
schema_generating: true
weight: 20
