id: gene_to_go_term_association
schema_generating: true
display_name: gene to go term association
document_category: gene to go term association
weight: 20
fields:
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: subject
  description: gene, product or macromolecular complex that has the function associated
    with the GO term
  display_name: gene to go term association_subject
- id: object
  description: class describing the activity, process or localization of the gene
    product
  display_name: gene to go term association_object
