id: gene_regulatory_relationship
schema_generating: true
description: A regulatory relationship between two genes
display_name: gene regulatory relationship
document_category: gene regulatory relationship
weight: 20
fields:
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: relation
  description: the direction is always from regulator to regulated
  display_name: gene regulatory relationship_relation
- id: subject
  display_name: gene regulatory relationship_subject
- id: object
  display_name: gene regulatory relationship_object
