id: gene_product
schema_generating: true
description: The functional molecular product of a single gene. Gene products are
  either proteins or functional RNA molecules
display_name: gene product
document_category: gene product
weight: 20
fields:
- id: category
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: category
  cardinality: multi
- id: in_taxon
  description: connects a thing to a class representing a taxon
  display_name: in taxon
  cardinality: multi
- id: has_biological_sequence
  description: connects a genomic feature to its sequence
  display_name: has biological sequence
- id: id
  description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for a thing
  display_name: name
- id: description
  description: a human-readable description of a thing
  display_name: description
- id: synonym
  description: Alternate human-readable names for a thing
  display_name: synonym
  cardinality: multi
- id: xref
  description: Alternate CURIEs for a thing
  display_name: xref
  cardinality: multi
