id: gene_to_gene_product_relationship
schema_generating: true
description: A gene is transcribed and potentially translated to a gene product
display_name: gene to gene product relationship
document_category: gene to gene product relationship
weight: 20
fields:
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: subject
  display_name: gene to gene product relationship_subject
- id: object
  display_name: gene to gene product relationship_object
- id: relation
  display_name: gene to gene product relationship_relation
