id: genotype_to_genotype_part_association
schema_generating: true
description: Any association between one genotype and a genotypic entity that is a
  sub-component of it
display_name: genotype to genotype part association
document_category: genotype to genotype part association
weight: 20
fields:
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: predicate
  display_name: genotype to genotype part association_predicate
- id: subject
  description: parent genotype
  display_name: genotype to genotype part association_subject
- id: object
  description: child genotype
  display_name: genotype to genotype part association_object
