description: Any association between one genotype and a genotypic entity that is a
  sub-component of it
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- genotype to genotype part association
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- genotype to genotype part association
fields:
- description: A unique identifier for an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association_id
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association slot
  id: association_slot
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - genotype to genotype part association relation
  id: relation
- description: parent genotype
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - genotype to genotype part association subject
  id: subject
- description: child genotype
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - genotype to genotype part association object
  id: object
id: genotype_to_genotype_part_association
schema_generating: true
weight: 20
