description: Any association between a genotype and a gene. The genotype have have
  multiple variants in that gene or a single one. There is no assumption of cardinality
display_name: genotype to gene association
document_category: genotype to gene association
fields:
- {description: A unique identifier for a thing. Must be either a CURIE shorthand
    for a URI or a complete URI, display_name: id, id: id}
- {description: A human-readable name for a thing, display_name: name, id: name}
- {description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag, display_name: category, id: category}
- {description: A grouping for any relationship type that holds between any two things,
  display_name: related to, id: related_to}
- {description: A grouping for any property that holds between a node and a value,
  display_name: node property, id: node_property}
- {description: An IRI for the node. This is determined by the id using expansion
    rules., display_name: iri, id: iri}
- {description: a long-form human readable name for a thing, display_name: full name,
  id: full_name}
- {description: a human-readable description of a thing, display_name: description,
  id: description}
- {description: more commonly used for gene symbols in yeast, display_name: systematic
    synonym, id: systematic_synonym}
- {description: connects an association to the type of association (e.g. gene to phenotype),
  display_name: association type, id: association_type}
- {description: 'if set to true, then the association is negated i.e. is not true',
  display_name: negated, id: negated}
- {cardinality: multi, description: connects an association to qualifiers that modify
    or qualify the meaning of that association, display_name: qualifiers, id: qualifiers}
- {cardinality: multi, description: connects an association to publications supporting
    the association, display_name: publications, id: publications}
- {description: 'connects an association to the agent (person, organization or group)
    that provided it', display_name: provided by, id: provided_by}
- {description: any slot that relates an association to another entity, display_name: association
    slot, id: association_slot}
- {description: the relationship type by which a subject is connected to an object
    in an association, display_name: genotype to gene association relation, id: relation}
- {description: 'connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.',
  display_name: genotype to gene association subject, id: subject}
- {description: 'connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.',
  display_name: genotype to gene association object, id: object}
id: genotype_to_gene_association
schema_generating: true
weight: 20
