id: genotype_to_phenotypic_feature_association
schema_generating: true
description: Any association between one genotype and a phenotypic feature, where
  having the genotype confers the phenotype, either in isolation or through environment
display_name: genotype to phenotypic feature association
document_category: genotype to phenotypic feature association
weight: 20
fields:
- id: object
  description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: object
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: relation
  display_name: genotype to phenotypic feature association_relation
- id: subject
  description: genotype that is associated with the phenotypic feature
  display_name: genotype to phenotypic feature association_subject
- id: sex_qualifier
  description: a qualifier used in a phenotypic association to state whether the association
    is specific to a particular sex.
  display_name: sex qualifier
- id: description
  description: A description of specific aspects of this phenotype, not otherwise
    covered by the phenotype ontology class
  display_name: entity to phenotypic feature association_description
- id: frequency_qualifier
  description: a qualifier used in a phenotypic association to state how frequent
    the phenotype is observed in the subject
  display_name: frequency qualifier
- id: severity_qualifier
  description: a qualifier used in a phenotypic association to state how severe the
    phenotype is in the subject
  display_name: severity qualifier
- id: onset_qualifier
  description: a qualifier used in a phenotypic association to state when the phenotype
    appears is in the subject
  display_name: onset qualifier
