id: genotype
schema_generating: true
description: An information content entity that describes a genome by specifying the
  total variation in genomic sequence and/or gene expression, relative to some extablished
  background
display_name: genotype
document_category: genotype
weight: 20
fields:
- id: id
  description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for a thing
  display_name: name
- id: category
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: category
  cardinality: multi
- id: in_taxon
  description: connects a thing to a class representing a taxon
  display_name: in taxon
  cardinality: multi
- id: has_biological_sequence
  description: connects a genomic feature to its sequence
  display_name: has biological sequence
- id: has_zygosity
  display_name: has zygosity
