description: A functional association between a macromolecular machine (gene, gene
  product or complex) and a cellular component (as represented in the GO cellular
  component branch), where the entity carries out its function in the cellular component
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- macromolecular machine to cellular component association
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- macromolecular machine to cellular component association
fields:
- description: A unique identifier for an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association_id
  id: id
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - relation
  id: relation
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association slot
  id: association_slot
- description: gene, product or macromolecular complex that has the function associated
    with the GO term
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - functional association subject
  id: subject
- description: class describing the activity, process or localization of the gene
    product
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - macromolecular machine to cellular component association object
  id: object
id: macromolecular_machine_to_cellular_component_association
schema_generating: true
weight: 20
