description: a databased entity or concept/class
display_name: !!python/object/new:biolinkml.meta.ClassDefinitionName
- named thing
document_category: !!python/object/new:biolinkml.meta.ClassDefinitionName
- named thing
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - id
  id: id
- description: A human-readable name for a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - name
  id: name
- cardinality: multi
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - category
  id: category
- cardinality: multi
  description: A relationship that is asserted between two named things
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - related to
  id: related_to
- cardinality: multi
  description: holds between any two entities that directly or indirectly interact
    with each other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - interacts with
  id: interacts_with
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - node property
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - iri
  id: iri
- cardinality: multi
  description: Alternate human-readable names for a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - synonym
  id: synonym
- description: a long-form human readable name for a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - full name
  id: full_name
- description: a human-readable description of a thing
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - description
  id: description
- cardinality: multi
  description: more commonly used for gene symbols in yeast
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - systematic synonym
  id: systematic_synonym
- cardinality: multi
  description: holds between two entities that make physical contact as part of some
    interaction
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - physically interacts with
  id: physically_interacts_with
- cardinality: multi
  description: describes an entity that has a direct affect on the state or quality
    of another existing entity. Use of the 'affects' predicate implies that the affected
    entity already exists, unlike predicates such as 'affects risk for' and 'prevents,
    where the outcome is something that may or may not come to be.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects
  id: affects
- cardinality: multi
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - regulates
  id: regulates
- cardinality: multi
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - positively regulates
  id: positively_regulates
- cardinality: multi
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - negatively regulates
  id: negatively_regulates
- cardinality: multi
  description: describes a relationship where one entity degrades or interferes with
    the structure, function, or occurrence of another.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - disrupts
  id: disrupts
- cardinality: multi
  description: holds between two biological entities that have common evolutionary
    origin
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - homologous to
  id: homologous_to
- cardinality: multi
  description: a homology relationship that holds between entities (typically genes)
    that diverged after a duplication event.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - paralogous to
  id: paralogous_to
- cardinality: multi
  description: a homology relationship between entities (typically genes) that diverged
    after a speciation event.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - orthologous to
  id: orthologous_to
- cardinality: multi
  description: a homology relationship characterized by an interspecies (horizontal)
    transfer since the common ancestor.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - xenologous to
  id: xenologous_to
- cardinality: multi
  description: holds between two entities that are co-located in the same aggregate
    object, process, or spatio-temporal region
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - coexists with
  id: coexists_with
- cardinality: multi
  description: holds between two entities that are observed to be located in the same
    place.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - colocalizes with
  id: colocalizes_with
- cardinality: multi
  description: holds between two entities where exposure to one entity alters the
    chance of developing the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - affects risk for
  id: affects_risk_for
- cardinality: multi
  description: holds between two entities where exposure to one entity increases the
    chance of developing the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - predisposes
  id: predisposes
- cardinality: multi
  description: holds between two entities where the occurrence, existence, or activity
    of one causes or contributes to the occurrence or generation of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - contributes to
  id: contributes_to
- cardinality: multi
  description: holds between two entities where the occurrence, existence, or activity
    of one causes the occurrence or  generation of the other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - causes
  id: causes
- cardinality: multi
  description: holds between an entity whose application or use reduces the likelihood
    of a potential outcome. Typically used to associate a chemical substance, exposure,
    activity, or medical intervention that can prevent the onset a disease or phenotypic
    feature.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - prevents
  id: prevents
- cardinality: multi
  description: holds between a process and a material entity or site within which
    the process occurs
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - occurs in
  id: occurs_in
- cardinality: multi
  description: holds between a material entity and a material entity or site within
    which it is located (but of which it is not considered a part)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - located in
  id: located_in
- cardinality: multi
  description: holds between material entity or site and a material entity that is
    located within it (but not considered a part of it)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - location of
  id: location_of
- cardinality: multi
  description: holds between an entity and some other entity it approximates for purposes
    of scientific study, in virtue of its exibiting similar features of the studied
    entity.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - model of
  id: model_of
- cardinality: multi
  description: holds between entties that overlap in their extents (materials or processes)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - overlaps
  id: overlaps
- cardinality: multi
  description: holds between wholes and their parts (material entities or processes)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - has part
  id: has_part
- cardinality: multi
  description: holds between parts and wholes (material entities or processes)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - part of
  id: part_of
- cardinality: multi
  description: holds between a continuant and a process, where the continuant is somehow
    involved in the process
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - participates in
  id: participates_in
- cardinality: multi
  description: holds between a continuant and a process or function, where the continuant
    actively contributes to part or all of the process or function it realizes
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - actively involved in
  id: actively_involved_in
- cardinality: multi
  description: holds between a continuant and process or function, where the continuant
    alone has the ability to carry out the process or function.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - capable of
  id: capable_of
- cardinality: multi
  description: holds between two distinct material entities, the old entity and the
    new entity, in which the new entity begins to exist when the old entity ceases
    to exist, and the new entity inherits the significant portion of the matter of
    the old entity
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - derives into
  id: derives_into
- cardinality: multi
  description: holds between two distinct material entities, the new entity and the
    old entity, in which the new entity begins to exist when the old entity ceases
    to exist, and the new entity inherits the significant portion of the matter of
    the old entity
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - derives from
  id: derives_from
- cardinality: multi
  description: used in SemMedDB for linking things like dysfunctions and processes
    to some disease or syndrome
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - manifestation of
  id: manifestation_of
- cardinality: multi
  description: holds between a material entity and a product that is generated through
    the intentional actions or functioning of the material entity
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - produces
  id: produces
- cardinality: multi
  description: holds between two entities that are considered equivalent to each other
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - same as
  id: same_as
- description: date on which thing was created. This can be applied to nodes or edges
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - creation date
  id: creation_date
- description: date on which thing was updated. This can be applied to nodes or edges
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - update date
  id: update_date
- description: description of chemical compound based on element symbols
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - has chemical formula
  id: has_chemical_formula
- display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - aggregate statistic
  id: aggregate_statistic
- cardinality: multi
  description: connects a sequence variant to a class describing the molecular consequence.
    E.g.  SO:0001583
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - has molecular consequence
  id: has_molecular_consequence
- description: The value in a property-value tuple
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - filler
  id: filler
- description: TODO
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - interbase coordinate
  id: interbase_coordinate
id: named_thing
schema_generating: true
weight: 20
