id: pairwise_gene_to_gene_interaction
schema_generating: true
description: An interaction between two genes or two gene products. May be physical
  (e.g. protein binding) or genetic (between genes). May be symmetric (e.g. protein
  interaction) or directed (e.g. phosphorylation)
display_name: pairwise gene to gene interaction
document_category: pairwise gene to gene interaction
weight: 20
fields:
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: subject
  description: the subject gene in the association. If the relation is symmetric,
    subject vs object is arbitrary. We allow a gene product to stand as proxy for
    the gene or vice versa
  display_name: gene to gene association_subject
- id: object
  description: the object gene in the association. If the relation is symmetric, subject
    vs object is arbitrary. We allow a gene product to stand as proxy for the gene
    or vice versa
  display_name: gene to gene association_object
- id: relation
  description: interaction relationship type
  display_name: pairwise gene to gene interaction_relation
