id: pathognomonicity_quantifier
schema_generating: true
description: A relationship quantifier between a variant or symptom and a disease,
  which is high when the presence of the feature implies the existence of the disease
display_name: pathognomonicity quantifier
document_category: pathognomonicity quantifier
weight: 20
