id: population_to_population_association
schema_generating: true
description: An association between a two populations
display_name: population to population association
document_category: population to population association
weight: 20
fields:
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: subject
  description: the population that form the subject of the association
  display_name: population to population association_subject
- id: object
  description: the population that form the object of the association
  display_name: population to population association_object
- id: relation
  description: A relationship type that holds between the subject and object populations.
    Standard mereological relations can be used. E.g. subject part-of object, subject
    overlaps object. Derivation relationships can also be used
  display_name: population to population association_relation
