id: sequence_association
schema_generating: true
description: An association between a sequence feature and a genomic entity it is
  localized to.
display_name: sequence association
document_category: sequence association
weight: 20
fields:
- id: subject
  description: connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: subject
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: object
  description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: object
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
