id: variant_to_population_association
schema_generating: true
description: An association between a variant and a population, where the variant
  has particular frequency in the population
display_name: variant to population association
document_category: variant to population association
weight: 20
fields:
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: subject
  description: an allele that has a certain frequency in a given population
  display_name: variant to population association_subject
- id: object
  description: the population that is observed to have the frequency
  display_name: variant to population association_object
- id: has_quotient
  description: frequency of allele in population, expressed as a number with allele
    divided by number in reference population, aka allele frequency
  display_name: variant to population association_has quotient
- id: has_count
  description: number in object population that carry a particular allele, aka allele
    count
  display_name: variant to population association_has count
- id: has_total
  description: number all populations that carry a particular allele, aka allele number
  display_name: variant to population association_has total
- id: has_percentage
  description: equivalent to has quotient multiplied by 100
  display_name: has percentage
- id: frequency_qualifier
  description: a qualifier used in a phenotypic association to state how frequent
    the phenotype is observed in the subject
  display_name: frequency qualifier
