display_name: !!python/object/new:biolinkml.meta.ClassDefinitionName
- variant to disease association
document_category: !!python/object/new:biolinkml.meta.ClassDefinitionName
- variant to disease association
fields:
- display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - variant to disease association_subject
  id: subject
- display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - variant to disease association_relation
  id: relation
- display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - variant to disease association_object
  id: object
- description: A unique identifier for an association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association_id
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association slot
  id: association_slot
- description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - edge label
  id: edge_label
- description: a qualifier used in a phenotypic association to state how frequent
    the phenotype is observed in the subject
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - frequency qualifier
  id: frequency_qualifier
- description: a qualifier used in a phenotypic association to state how severe the
    phenotype is in the subject
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - severity qualifier
  id: severity_qualifier
- description: a qualifier used in a phenotypic association to state when the phenotype
    appears is in the subject
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - onset qualifier
  id: onset_qualifier
id: variant_to_disease_association
schema_generating: true
weight: 20
