description: an ontology class that describes a functional aspect of a gene, gene
  prodoct or complex
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- gene ontology class
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- gene ontology class
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - id
  id: id
- description: A human-readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - name
  id: name
- cardinality: multi
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - category
  id: category
- cardinality: multi
  description: An alternate identifier for the entity, provided by the source database
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - has alternate identifier
  id: has_alternate_identifier
- cardinality: multi
  description: A database cross-reference for the entity, provided by a separate database
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - has xref
  id: has_xref
- cardinality: multi
  description: Alternate labels for an entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - has synonym
  id: has_synonym
- description: A grouping for any relationship type that holds between any two things
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - related to
  id: related_to
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - node property
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - iri
  id: iri
- cardinality: multi
  description: Alternate human-readable names for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - synonym
  id: synonym
- description: a long-form human readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - full name
  id: full_name
- description: a human-readable description of a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - description
  id: description
- description: more commonly used for gene symbols in yeast
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - systematic synonym
  id: systematic_synonym
- description: holds between two classes where the domain class is a specialization
    of the range class
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - subclass of
  id: subclass_of
id: gene_ontology_class
schema_generating: true
weight: 20
