display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- anatomical entity to anatomical entity association
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName
- anatomical entity to anatomical entity association
fields:
- description: A unique identifier for an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association_id
  id: id
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - relation
  id: relation
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - association slot
  id: association_slot
- description: connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - anatomical entity to anatomical entity association subject
  id: subject
- description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName
  - anatomical entity to anatomical entity association object
  id: object
id: anatomical_entity_to_anatomical_entity_association
schema_generating: true
weight: 20
