description: A gene is a collection of transcripts
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [transcript
    to gene relationship]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [transcript
    to gene relationship]
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [id]
  id: id
- description: A human-readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [name]
  id: name
- description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [category]
  id: category
- description: URI expansion of CURIE
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [uri]
  id: uri
- description: A grouping for any relationship type that holds between any two things
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [related
      to]
  id: related_to
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [node property]
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [iri]
  id: iri
- description: a long-form human readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [full name]
  id: full_name
- description: a human-readable description of a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [description]
  id: description
- description: more commonly used for gene symbols in yeast
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [systematic
      synonym]
  id: systematic_synonym
- description: Narrative text describing the entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [title]
  id: title
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      type]
  id: association_type
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [negated]
  id: negated
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [relation]
  id: relation
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [qualifiers]
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [publications]
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [provided
      by]
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      slot]
  id: association_slot
- description: connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [transcript
      to gene relationship subject]
  id: subject
- description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [transcript
      to gene relationship object]
  id: object
id: transcript_to_gene_relationship
schema_generating: true
weight: 20
